### ISSUE TITLE
考虑处理一下 flutter 引入 uniapp 吗？

### ISSUE THREAD

**Issue by barretzhi** [app-case-community/uniapp-flutter#1]
现有项目用的是flutter,原版的项目用的是uniapp，功能太多，想直接应用过来使用

**Comment by wraptor** [comment]
+1，有多个子系统各使用uniapp开发了多个小程序项目，boss想做个app包含所有子系统功能，如果有flutter能直接引uniapp小程序，那就直接用flutter开发个主体app，子系统用引入的方式了

**Comment by snice** [comment]
可以，但是只能通过uni小程序SDK集成，有兴趣，可以加入QQ群 912719310 讨论
