### ISSUE TITLE
这是uniapp项目集成flutter页面或组件吗？但是云打包后运行到模拟器闪退了，是太久没更新版本有问题吗？

### ISSUE THREAD

**Issue by seepine** [app-case-community/uniapp-flutter#2]
另外`uniapp-flutter-module`项目也不行，运行报错，大佬有空更新一下吗
![image](https://user-images.githubusercontent.com/93666053/184364000-5a062cc5-2862-46b8-a633-869c909300bb.png)

**Comment by snice** [comment]
需要自己改下build.gradle，16改成17

**Comment by seepine** [comment]
> 需要自己改下build.gradle，16改成17

不行哦
